from .grupo_service import GrupoService
from .area_service import AreaService
from .grado_service import GradoService
from .departamento_service import DepartamentoService
from .facultad_service import FacultadService
from .categoria_cargo_service import CategoriaCargoService
from .tipo_dedicacion_service import TipoDedicacionService
from .tipo_especialidad_service import TipoEspecialidadService
from .orientacion_service import OrientacionService
from .materia_service import MateriaService
from .plan_service import PlanService
from .especialidad_service import EspecialidadService
from .cargo_service import CargoService
from .alumno_service import AlumnoService
from .universidad_service import UniversidadService