from .grupo import Grupo
from .area import Area
from .grado import Grado
from .departamento import Departamento
from .categoria_cargo import CategoriaCargo
from .tipo_dedicacion import TipoDedicacion
from .tipo_especialidad import TipoEspecialidad
from .cargo import Cargo
from .facultad import Facultad
from .universidad import Universidad
from .orientacion import Orientacion
from .materia import Materia
from .plan import Plan
from .especialidad import Especialidad
from .relations import autoridades_materias
from .autoridad import Autoridad
from .tipo_documento import TipoDocumento
from .alumno import Alumno

